[tool.poetry]
name = "scikit-explain"
version = "0.1.0"
description = "This package is a toolkit of eXplainable Artificial Integillence (XAI) methods to interpret sklearn models."
authors = ["Arthur Selle Jacobs <asjacobs@inf.ufrgs.br>"]
packages = [ { include = "skexplain"} ]


[tool.poetry.dependencies]
python = ">=3.7,<3.9"
numpy = "^1.18.5"
scipy = "^1.4.1"
pandas = "^1.1.0"
pydotplus = "^2.0.2"
scikit-learn = "^0.23.2"
matplotlib = "^3.3.1"
imbalanced-learn = "^0.7.0"
rootpath = "^0.1.1"
keras = "^2.4.3"
ipython = "^7.18.1"
lime = "^0.2.0"
eli5 = "^0.10.1"
seaborn = "^0.11.0"
pingouin = "^0.3.8"
pyshark = "^0.4.2"
interpret = "^0.2.4"
jupyter = "^1.0.0"
setuptools = "^57.0.0"
torch = "^1.10.0"
prettytable = "3.0.0"
termcolor = "^1.1.0"
shap = "^0.40.0"
PyNaCl = "1.4.0"
autogluon = "^0.3.1"

[tool.poetry.dev-dependencies]


[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12", "setuptools>=^57.0.0"]
build-backend = "poetry.masonry.api"
